language: node_js
node_js:
  - 4

notifications:
  slack:
    - secure: "zzLwzguV/TKpNS5Qao3hve83qkTuKf+gCJaSl8UVbc+vdezzV/FJ8uIstUcYvdY/Cjd+A0uOVQaTIglnZ5DCB/1uhQjhMAFCMKpqbZ594uHJdyxqD+f6Ac3ri14fZCZHU+Y/MtbNRNqepwCz/KYmrevWlDUJLRWMi47206FWACXyz1YSHFgXq+cP19erJrNRdfvcMtHNG6gX8eRMj9mczQmiBeDNRyFcWEDBHMPiYip5kymrI7OpGUqQEqu2M+5h/I/UbIhoe851OzdE77hh3uvfUTvbFP8t7EIKjc1JhPSHxoYcYDBH9kzFo0P88HDtMDI8W1CrfgdmmX94gxtJj2o0Yki1ydxWBCLQ9OfRFD8ibt9FAAjbr9pcjRZDgbZLwk/hwImnujUBjloYYX6iQ1xjMIvUwNMBm2IcliclatZuYiv5A0IV7E/rlw8dOJDxWPZwdtWqRx6Gcv/+4rGeh3C2xP7LEWg4S8Jmhz3QdChmqX566H6xXGO0nF9CQ1oRzvIt460vNTk37jKSkIOQ2NUlDOyZx2AUEMVwkEFLGWCXiGmUPOp73GpTcvpUSleJASvVdvOjCV8ERMGZA49DpeEp3PkZbgw2g+EKvrcnCuB/tOjtExks9y9QgLScm0BS/PetH7s5UObDTCmIf5dAE6CMahgWlA9Qko0W+l/OMvE="
